### ISSUE TITLE
Move Project to Separate Organization

### ISSUE THREAD

**Issue by mattt** [Jounce/Surge#130]
Although this project is hosted under my personal GitHub account, my direct involvement has been substantially less than others who stepped up to maintain it over the years — in particular, @rfdickerson, @alejandro-isaza, and @regexident. I think moving it to a separate org would better serve to honor everyone's contributions (https://github.com/mattt/Surge/graphs/contributors).

My first choice for an org name would be @Surge, but that's claimed by an apparently defunct project. Over the years, I've made several attempts to reach out to the owners (with no response), and even went as far to contact GitHub support (who reported that the owner isn't willing to give up the namespace).

I'd also considered using an entirely different name as a new umbrella org for this project and https://github.com/mattt/euler (as well as any other math-related Swift libraries to come), but I've yet to come up with a good name.

Having thought about this for a few years now, I wanted to bring this up for public discussion.

**Comment by mattt** [comment]
@regexident: What are your thoughts about migrating this into a separate organization? Any thoughts for a name?

**Comment by BilalReffas** [comment]
I think it's a great idea @mattt. What do you guys think about the org name Rosenblatt ? Wiki about [him](https://en.wikipedia.org/wiki/Frank_Rosenblatt)

**Comment by regexident** [comment]
@mattt I inquired with Github's support about the situation, now that 5 years have passed since the last activity in the existing organization. I'll let you know when (and what) I get a response.

@BilalReffas An issue I see with Rosenblatt is that it is neither closely related to the "accelerate" or "surge", nor is Surge a framework for neural networks. It's a general purpose vector-processing framework ("vector" as in [vectorizing](https://en.wikipedia.org/wiki/Automatic_vectorization)).

Apart from **providing a workspace that's less** biased towards a single contributor the other big benefit of moving Surge into an organization should be to have an **easily recognizable, memorable and —most importantly— obvious** umbrella name for Surge and any of its potential future sister packages (as we might one day decide to split up/grow Surge into more isolated and modular sub-packages, such as "SurgeLinAlg", "SurgeDSP", …).
A seemingly random name, such as Rosenblatt would not qualify for the latter, imho.

As such if at all possible we should aim to get ahold of "github.com/surge", imho.

**Comment by regexident** [comment]
Update: The account [/surge](https://github.com/surge) unfortunately remains unavailable, according to user-support.  
I managed however to get my hands on [/jounce](https://github.com/jounce) through the Github [Name Squatting Policy](https://help.github.com/en/articles/github-username-policy).

"Wait", you ask, "what's the deal with `/jounce/`?" 🤨

Surge's README gives a partial answer:

> Curious about the name Surge? Back in the mid 90's, Apple, IBM, and Motorola teamed up to create AltiVec (a.k.a the Velocity Engine), which provided a SIMD instruction set for the PowerPC architecture. When Apple made the switch to Intel CPUs, AltiVec was ported to the x86 architecture and rechristened Accelerate. The derivative of Accelerate (and second derivative of Velocity) is known as either jerk, jolt, surge, or lurch, hence the name of this library.

Here's the deal: **jounce** is to **surge** what **surge** is to **acceleration**.

The derivatives of displacement are: **Displacement** > **Velocity** > **Acceleration** > **Jerk** / **Surge** > **Snap** / **Jounce** > **Crackle** > **Pop** ([more into](http://wordpress.mrreid.org/2013/12/11/jerk-jounce-snap-crackle-and-pop/))

([/snap](https://github.com/snap), as one might expect was taken and active.\)

@mattt if you think [/jounce](https://github.com/jounce) was a good fit for Surge I'd happily transfer the organization over to you.

**Comment by mattt** [comment]
@regexident Thanks for reaching out to GitHub support about @surge. I agree that this would have been ideal, but I think @jounce is a great alternative. Let's go with that!

Here's my proposed migration process:

1. Add me as an admin to @jounce
2. I'll transfer Surge to @jounce and quickly create a fork at @mattt/surge to serve as a redirect
3. I'll submit a PR to update all references in the README / pod spec / package manifest to point to the new URL

Sound good?

**Comment by regexident** [comment]
Awesome I just sent you an invitation. :)
