### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by SharanSMenon** [Jounce/Surge#180]
Is this project Dead? There hasn't been activity for a long time.

**Comment by SharanSMenon** [comment]
Its been over a year since the last commit

**Comment by jkalias** [comment]
That’s an interesting question, I was thinking about the same thing. Any feedback from the maintainers?

**Comment by regexident** [comment]
@SharanSMenon @jkalias sorry for taking so long to respond!

I joined the project in end of 2019 as the main driving force behind a major cleanup and refactoring of Surge, taking over most of the active maintenance work since then.

(Disclaimer: I can obviously only speak for myself.)

For the most part Surge is feature-complete and mature and thus doesn't nee much if any active development.

While performing those aforementioned major API cleanups and refactors I found that the way that Surge is implemented today leads to incredible amounts of redundant code that's extremely hard to maintain and keep aligned. Just keeping the README's function inventory in sync with the actual implementation has been quite a task of its own.

This is not to say however that we (or should I say I) haven't been looking into possible improvements to the framework:

Surge currently consists of :

- 323 `public` functions
- 129 `internal` functions
- 272 test functions
- 115 benchmark functions

All of which were written by hand, even though the vast majority of them are highly redundant in both code and structure.

Basically all of the `public` functions can be effectively classified into three major buckets by function arity:

- unary (e.g. `log2`, `sqrt`, …)
- binary (e.g. `sub`, `add`, `exp`, …)
- ternary (e.g. `muladd`)

Given this Surge would be a perfect use of templating. I tried [Sourcery](https://github.com/krzysztofzablocki/Sourcery) but quickly found that it simply wasn't up to the task though, since it requires valid Swift as input. And working with gyp or any other templating language would greatly obfuscate the source code of Surge, introducing a non-trivial learning curve and burden on new contributors.

Further more currently Surge for the most part only provides functions that produce a new tensor.
Only a very select few functions provide operators that work with in-place (i,e `inout`) semantics (e.g. `-=`, `+=`, …), modifying an existing tensor, rather than allocating a new one, each time. Even though basically all Accelerate functions wrapped by Surge would support in-place semantics.

Roughly two years ago I had created a (failed/abandoned) [experimental re-imagination](https://github.com/Jounce/SurgeNeue) of Surge with the intention of evaluating the feasibility of such performance and efficiency improvements. I quickly realized though that with the lack of any proper meta-programming capabilities in Swift (e.g. macros, code-gen, syntax-plugins, etc) such a framework would quickly suffer from the very same issues that Surge is suffering from today.

I have however been pondering with giving SurgeNeue a second try at some point. But having been rather busy with other stuff and having had no immediate need for Surge in my current day-to-day work no actual work has happened in this respect since.

**Comment by SharanSMenon** [comment]
Thank you for letting us know!

**Comment by jonbirge** [comment]
We appreciate the effort, @regexident! One suggestion, if you're interested, would be to aggressively descope Surge in a way that would make it much easier to maintain, while still being very useful. For example, it's probably rough to maintain code for both Float and Double versions of everything. However, I don't think anybody would mind if the Framework only supported Double versions of everything. Likewise, there are probably a lot of functions that aren't terribly important to support, or can be written as trivial wrappers for other functions. Division of a matrix by a scalar, for example, could just call the scalar multiplication function. So, between arithmetic inverses and dropping Floats, that's a lot of simplification right there.
